apiVersion: apps/v1
kind: Deployment
metadata:
  name: tennis-app-deployment
  namespace: tennis-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tennis-app
  template:
    metadata:
      labels:
        app: tennis-app
    spec:
      containers:
        - name: tennis-app
          image: ghcr.io/stepanadamek/tennis-court-reservation:staging-latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: tennis-app-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: tennis-app-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tennis-app-secret
                  key: SPRING_DATASOURCE_PASSWORD
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15