apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: tennis-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: tennis_reservation_db
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: tennis-app-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tennis-app-secret
                  key: POSTGRES_PASSWORD